<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-11-10 15:05

$extensionPath = t3lib_extMgm::extPath('cicbase');
return array(
	'tx_cicbase_domain_model_address' => $extensionPath . 'Classes/Domain/Model/Address.php',
	'tx_cicbase_domain_model_digitalasset' => $extensionPath . 'Classes/Domain/Model/DigitalAsset.php',
	'tx_cicbase_domain_model_latlng' => $extensionPath . 'Classes/Domain/Model/LatLng.php',
	'tx_cicbase_domain_model_state' => $extensionPath . 'Classes/Domain/Model/State.php',
	'tx_cicbase_domain_model_zip' => $extensionPath . 'Classes/Domain/Model/Zip.php',
	'tx_cicbase_domain_repository_digitalassetrepository' => $extensionPath . 'Classes/Domain/Repository/DigitalAssetRepository.php',
	'tx_cicbase_domain_repository_staterepository' => $extensionPath . 'Classes/Domain/Repository/StateRepository.php',
	'tx_cicbase_domain_repository_ziprepository' => $extensionPath . 'Classes/Domain/Repository/ZipRepository.php',
	'tx_cicbase_persistence_repository' => $extensionPath . 'Classes/Persistence/Repository.php',
	'tx_cicbase_service_geolocationservice' => $extensionPath . 'Classes/Service/GeolocationService.php',
	'tx_cicbase_viewhelpers_addslashesviewhelper' => $extensionPath . 'Classes/ViewHelpers/AddSlashesViewHelper.php',
	'tx_cicbase_viewhelpers_forchunkviewhelper' => $extensionPath . 'Classes/ViewHelpers/ForChunkViewHelper.php',
	'tx_cicbase_viewhelpers_forcommalistviewhelper' => $extensionPath . 'Classes/ViewHelpers/ForCommaListViewHelper.php',
	'tx_cicbase_viewhelpers_imageresourceviewhelper' => $extensionPath . 'Classes/ViewHelpers/ImageResourceViewHelper.php',
	'tx_cicbase_viewhelpers_lastimageresourceinfoviewhelper' => $extensionPath . 'Classes/ViewHelpers/LastImageResourceInfoViewHelper.php',
	'tx_cicbase_viewhelpers_rawviewhelper' => $extensionPath . 'Classes/ViewHelpers/RawViewHelper.php',
	'tx_cicbase_viewhelpers_striplinebreaksviewhelper' => $extensionPath . 'Classes/ViewHelpers/StripLinebreaksViewHelper.php',
	'tx_cicbase_viewhelpers_urlencodeviewhelper' => $extensionPath . 'Classes/ViewHelpers/UrlEncodeViewHelper.php',
	'tx_cicbase_scheduler_task' => $extensionPath . 'Classes/Scheduler/Task.php',
	'tx_cicbase_scheduler_fieldprovider' => $extensionPath . 'Classes/Scheduler/FieldProvider.php',
	'tx_cicbase_scheduler_fieldprovider' => $extensionPath . 'Classes/Scheduler/FieldProvider.php',
	'tx_cicbase_command_examplecommandcontroller' => $extensionPath . 'Classes/Command/ExampleCommandController.php'
);
?>