<?php
<<<<<<< HEAD
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-10-19 11:19

$extensionPath = t3lib_extMgm::extPath('cicbase');
$extensionClassesPath = $extensionPath . 'classes/';
return array(
	'tx_cicbase_domain_model_address' => $extensionClassesPath . 'Domain/Model/Address.php',
	'tx_cicbase_domain_model_digitalasset' => $extensionClassesPath . 'Domain/Model/DigitalAsset.php',
	'tx_cicbase_domain_model_latlng' => $extensionClassesPath . 'Domain/Model/LatLng.php',
	'tx_cicbase_domain_model_state' => $extensionClassesPath . 'Domain/Model/State.php',
	'tx_cicbase_domain_model_zip' => $extensionClassesPath . 'Domain/Model/Zip.php',
	'tx_cicbase_domain_repository_digitalassetrepository' => $extensionClassesPath . 'Domain/Repository/DigitalAssetRepository.php',
	'tx_cicbase_domain_repository_staterepository' => $extensionClassesPath . 'Domain/Repository/StateRepository.php',
	'tx_cicbase_domain_repository_ziprepository' => $extensionClassesPath . 'Domain/Repository/ZipRepository.php',
	'tx_cicbase_service_geolocationservice' => $extensionClassesPath . 'Service/GeolocationService.php',
	'tx_cicbase_viewhelpers_addslashesviewhelper' => $extensionClassesPath . 'ViewHelpers/AddSlashesViewHelper.php',
	'tx_cicbase_viewhelpers_imageresourceviewhelper' => $extensionClassesPath . 'ViewHelpers/ImageResourceViewHelper.php',
	'tx_cicbase_viewhelpers_lastimageresourceinfoviewhelper' => $extensionClassesPath . 'ViewHelpers/LastImageResourceInfoViewHelper.php',
	'tx_cicbase_viewhelpers_rawviewhelper' => $extensionClassesPath . 'ViewHelpers/RawViewHelper.php',
	'tx_cicbase_viewhelpers_striplinebreaksviewhelper' => $extensionClassesPath . 'ViewHelpers/StripLinebreaksViewHelper.php',
	'tx_cicbase_viewhelpers_urlencodeviewhelper' => $extensionClassesPath . 'ViewHelpers/UrlEncodeViewHelper.php',
	'tx_cicbase_persistence_repository' => $extensionClassPath . 'Persistence/Repository.php',
);

?>
