<?php

namespace CIC\Cicbase\ViewHelpers;

/**
	* Returns info on last imageResource generated by \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer or fluid
	*
	* @package TYPO3
	* @subpackage Fluid
	* @version
	*/

class LastImageResourceInfoViewHelper extends \TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper {
	/**
		* 
		* @param string $dimension should be one of 'width' or 'height'
		*
		* @return String
		* @author Gabe Blair <gabe@castironcoding.com>
	*/
	public function render($dimension = 'width') {
		return $GLOBALS['TSFE']->lastImgResourceInfo[($dimension == 'width' ? 0 : 1)];
	}
}

?>