<?php

/**
	* Returns info on last imageResource generated by tslib_cObj or fluid
	*
	* @package TYPO3
	* @subpackage Fluid
	* @version
	*/

class Tx_Cicbase_ViewHelpers_LastImageResourceInfoViewHelper extends Tx_Fluid_Core_ViewHelper_AbstractViewHelper {
	/**
		* 
		* @param string $dimension should be one of 'width' or 'height'
		*
		* @return String
		* @author Gabe Blair <gabe@castironcoding.com>
	*/
	public function render($dimension = 'width') {
		return $GLOBALS['TSFE']->lastImgResourceInfo[($dimension == 'width' ? 0 : 1)];
	}
}

?>